### PR TITLE
Editor import extraction

### PR DESCRIPTION
**Pull request by LoganMichalicek**
Import is now a button similar to record that opens a drawer. At the top shows existing layers, and below shows personal layers. If one of the existing layers also exists in the personal layers, they will toggle each other

### CODE REVIEW

**Comment by LoganMichalicek** [comment]
Also fixed ImportAudio typo

**Review by alexanderolvera — CHANGES_REQUESTED** [review]
Good work logan. I like the drawer. Thanks for doing this!

Small bug I found while testing. 

If I remove a layer and hit import, reopen the modal, that layer is checked again. 

image

**Comment by alexanderolvera** [comment]
As extra polish, maybe later if we have more important things to do. We should wrap the layers in a scrolling list so that the import button is always visible.

**Comment by LoganMichalicek** [comment]
["ImportAudio" as a constant is misspelled in Editor.jsx](https://trello.com/c/u31SOHjE/70-importaudio-as-a-constant-is-misspelled-in-editorjsx)

**Comment by LoganMichalicek** [comment]
[Turn import layers into a persistent drawer that contains both current and personal layers](https://trello.com/c/rpqHZXQk/79-turn-import-layers-into-a-persistent-drawer-that-contains-both-current-and-personal-layers)

**Review by alexanderolvera — COMMENTED** [review]
This does fix my last bug find. Great Job!

Now that this is fixed though we have another issue. 

I like the the original audio layers stay, but if you uncheck an original layer, then try to re-import it, it is available in the list, but does not actually import. 

We were aware of some strange biz like this might arise. Is this something we want to leave for later or fix now?

**Review by alexanderolvera — APPROVED** [review]
Looks great!

**Pull request merged**
